name = "abates"
main = "src/index.tsx"
compatibility_date = "2023-12-18"

[site]
bucket = "./assets"

[env.development]
IS_PROD = false

[env.production]
IS_PROD = true

[[env.production.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "abates-prod"
database_id = "5a5b7d01-dbdf-469a-b7a5-450e4926040e"

[[env.development.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "abates-dev"
database_id = "64bb1b33-e9df-4b20-890a-8b7ce07eae1d"

[env.development.vars]
COOKIE_NAME = "aces-auth"
CUSTOM_HEADER = "x-aces-auth"
API_KEY = "60173312-4e84-402f-98b4-ef01ceda1f7a"
COGNITIVE_KEYS = "Fe26.2*1*7cdc878167941fa23b2a828747b124860215922d9ec8d29e46fa2c84697d4fef*fqMrzitr5om4_qhE8Yf84w*XkA6-JilKNrRxv_1OuEjZpDJwAp_PORsY5wSeIZM3G9GwFLpgSpOFo3IDaQZ-6YTu7RkJmzPCsa8wrO_nnIPo44GEElxzjTbQ1FtpoJQrJtVf6w8YGceQzPBUGgDbqYqzIDP5QV3m8ZQhzz7wzreBMyYk9I6oNkczIsLLVnhjRAx8ZUESlK18ePIWsl5qqVF4r3g3tTQ68CHtINLpQF5jWEJFIpL3BEebyHaLHLL8HS09xW33xh5NCE3FsP4ZBFUmMQjMialKS8ZwFFVBUeEexbXahDvOjR2QnScDSXAnTXQALe_T8AmmUGYjIRMbyVyReieHM0B9cKXOg3prL3EUfl_P9rkXESudFTNow2ydsyPrx0nFoykjwNgVGWCkrWWrER4CUmI1ViALKTSRaVQ0HDpY9UnzhqTj7VFYNSZT8TKnz1SpXaCpKIqxb7LClkh*1686163853462*37e1513366e798e3bb589940f234b5dd55d058bc0b0d49fed5dc541ccbb13741*yNxL7zRXY8SnCXhugPaWXUfkxwrvew94NwQyMdTPo4I~2"
COOKIE_PASSWORD = "PJhb_GceyJ0-c0db97eXAiOiJ-KV1Q-LiOiJIU/zI1NiJ9="

[env.production.vars]
COOKIE_NAME = "aces-auth"
CUSTOM_HEADER = "x-aces-auth"
API_KEY = "60173312-4e84-402f-98b4-ef01ceda1f7a"
COGNITIVE_KEYS = "Fe26.2*1*7cdc878167941fa23b2a828747b124860215922d9ec8d29e46fa2c84697d4fef*fqMrzitr5om4_qhE8Yf84w*XkA6-JilKNrRxv_1OuEjZpDJwAp_PORsY5wSeIZM3G9GwFLpgSpOFo3IDaQZ-6YTu7RkJmzPCsa8wrO_nnIPo44GEElxzjTbQ1FtpoJQrJtVf6w8YGceQzPBUGgDbqYqzIDP5QV3m8ZQhzz7wzreBMyYk9I6oNkczIsLLVnhjRAx8ZUESlK18ePIWsl5qqVF4r3g3tTQ68CHtINLpQF5jWEJFIpL3BEebyHaLHLL8HS09xW33xh5NCE3FsP4ZBFUmMQjMialKS8ZwFFVBUeEexbXahDvOjR2QnScDSXAnTXQALe_T8AmmUGYjIRMbyVyReieHM0B9cKXOg3prL3EUfl_P9rkXESudFTNow2ydsyPrx0nFoykjwNgVGWCkrWWrER4CUmI1ViALKTSRaVQ0HDpY9UnzhqTj7VFYNSZT8TKnz1SpXaCpKIqxb7LClkh*1686163853462*37e1513366e798e3bb589940f234b5dd55d058bc0b0d49fed5dc541ccbb13741*yNxL7zRXY8SnCXhugPaWXUfkxwrvew94NwQyMdTPo4I~2"
COOKIE_PASSWORD = "PJhb_GceyJ0-c0db97eXAiOiJ-KV1Q-LiOiJIU/zI1NiJ9="